config/routes.rb
Rails.application.routes.draw do
  
  get 'tag/show'

  resources :post_attachments
  resources :posts

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/investment'
  get 'pages/csprojects'
  
  get 'seller' => 'listings#seller'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'tagged' => 'posts#tagged'
  get 'users' => 'users#index'

  root 'pages#home'

end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base

	mount_uploader :avatar, AvatarUploader
	belongs_to :post
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment.post, notice: 'Post attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_attachment }
      else
        format.html { render :edit }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :avatar)
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.erb
<%= form_for(@post_attachment) do |f| %>
  <% unless @post_attachment.avatar_url.nil? %>
    <%= image_tag @post_attachment.avatar_url, width: "50%" %><br />
  <% end %>
  <div class="form-group">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<div style="height:50px"></div>
<div class="container">
	
	<h1>Editing Post Attachment</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @post_attachment %> |
	<%= link_to 'Back', post_attachments_path %> |
	<%= link_to 'Destroy', post_attachment_path, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/post_attachments/index.html.erb
<div style="height:50px"></div>
<div class="container">
  <h1>Listing Post Attachments</h1>

  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Attachment</th>
        <th>Post ID</th>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @post_attachments.each do |post_attachment| %>
        <tr>
          <td><%= image_tag post_attachment.avatar_url, width: "50px" %></td>
          <td><%= post_attachment.post_id %></td>
          <td><%= post_attachment.avatar %></td>
          <td class ="center">
            <div class="btn-group btn-xs">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                Action <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" role="menu"> 
                <li><%= link_to 'Show', post_attachment %></li>
                <li><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></li>
                <li><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post attachment', new_post_attachment_path %>
</div>

app/views/post_attachments/new.html.erb
<div style="height:50px"></div>
<div class="container">

	<h1>New post_attachment</h1>

	<%= render 'form' %>

	<%= link_to 'Back', post_attachments_path %>
</div>

app/views/post_attachments/show.html.erb
<div style="height:50px"></div>
<div class="container">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Post:</strong>
	  <%= @post_attachment.post_id %>
	</p>

	<p>
	  <strong>Avatar:</strong>
	  <%= @post_attachment.avatar %>
	</p>

	<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
	<%= link_to 'Back', post_attachments_path %>
</div>