config/routes.rb
Rails.application.routes.draw do
  
  get 'tag/show'

  resources :post_attachments
  resources :posts

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/investment'
  get 'pages/csprojects'
  
  get 'seller' => 'listings#seller'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'tagged' => 'posts#tagged'
  get 'users' => 'users#index'

  root 'pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
	if Rails.env.development? 
		has_attached_file :image, :styles => { :medium => "500x>", :thumb => "100x100>" }, :default_url => "default.jpg",
			dependent: :destroy

	else
		has_attached_file :image, :styles => { :medium => "500x>", :thumb => "100x100>" }, :default_url => "default.jpg",
		    :storage => :dropbox,
	    	:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
	    	:path => ":style/:id_:filename",
	    	dependent: :destroy
	end
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	validates_attachment_presence :image
  	#validates :title, :description, presence: true
  	validates :address, :title, :FromDate, :ToDate, presence: true

  	geocoded_by :address
  	after_validation :geocode

	acts_as_taggable
	acts_as_taggable_on :tag_list

	has_many :post_attachments, dependent: :destroy
	accepts_nested_attributes_for :post_attachments

	validate :image_size_validation, :if => "image?"

	def image_size_validation
	    if image.size > 2.megabytes
	      errors.add(:base, "Image should be less than 2MB")
	    end
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @hash = Gmaps4rails.build_markers(Post.all) do |post, marker|
      marker.lat post.latitude
      marker.lng post.longitude
      marker.infowindow post.title
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post_attachments = @post.post_attachments.all
  end

  def new
   @post = Post.new
   @post_attachment = @post.post_attachments.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @tags = Post.tag_counts_on(:tags)
    
        respond_to do |format|
          if @post.save
            if params[:post_attachments]
              params[:post_attachments]['avatar'].each do |a|
                @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
              end
            end
            format.html { redirect_to @post, notice: 'Post was successfully created.' }
            format.json { render :show, status: :created, location: @post }
          else
            format.html { render :new }
            format.json { render json: @post.errors, status: :unprocessable_entity }
          end
        end

  end
  def update
    respond_to do |format|
      if @post.update(post_params)
        if params[:post_attachments]
          params[:post_attachments]['avatar'].each do |a|
            @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
          end
        end
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json

  def tagged
    if params[:tag].present?
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.index
    end
  end
  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
  end
  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :tag_list, :image, :avatar, :FromDate, :ToDate, :address, :latitude, :longitude, post_attachments_attributes: [:id, :post_id, :avatar])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">&times;</button>
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="form-group">
     <%= f.label :title %><br>
     <%= f.text_field :title, class: "form-control" %>
     <%= f.label :tags, "Tags (separated by commas)" %><br>
     <%= f.text_field :tag_list,class: "form-control"%><br>
     <%= f.label "From" %>&nbsp&nbsp<%= f.text_field :FromDate, class: "datepicker"%>
     <% content_for :javascripts do %>
       <%= javascript_tag do %>
          $(document).ready(function(){
            $('.datepicker').datepicker({
              format: "yyyy/mm/dd"
            });
          });
       <% end %>
     <% end %>
     <%= f.label "To" %>&nbsp&nbsp<%= f.text_field :ToDate, class: "datepicker" %>
     <br><br>
     <%= f.label :address %>
     <%= f.text_field :address, class: "form-control"%>
     <%= f.label :description %><br>
     <%= f.text_area :description, :size => "30x10", class: "form-control"%>
   </div>
   <div class="form-group">
     <%= f.label "Thumbnail" %><br>
     <%= f.file_field :image, class: "form-control" %>
   </div>
   <div>
     <%= f.label "Upload Files" %><br>
     <%= f.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]", class: "form-control"%>
   </div>

   <% if params[:controller] == "post" && params[:action] == "edit" %> 
     <% @post.post_attachments.each do |p| %>
       <%= image_tag p.avatar, :size => "200x200", class: "form-control" %>
     <% end %>
   <% end %>
   <br>
   <div class="form-group">
     <%= f.submit class: "btn btn-primary"%>
   </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<h1>Editing post</h1>

	<%= render 'form' %>

	<%= link_to '', posts_path, class: "glyphicon glyphicon-arrow-left" %> |
	<%= link_to '', edit_post_path(@post), class: "glyphicon glyphicon-edit" %> |
	<%= link_to '', post_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash" %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>World Travel Blog</h1>
    <head>
    <script type="text/javascript">
      jQuery(document).ready(function() {
        jQuery('#vmap').vectorMap({
            map: 'world_en',
            backgroundColor: '#a5bfdd',
            borderColor: '#818181',
            borderOpacity: 0.25,
            borderWidth: 1,
            color: '#f4f3f0',
            enableZoom: false,
            hoverColor: '#c9dfaf',
            hoverOpacity: null,
            normalizeFunction: 'linear',
            scaleColors: ['#b6d6ff', '#005ace'],
            selectedColor: '#c9dfaf',
            selectedRegion: null,
            showTooltip: true,
            onRegionClick: function (event, code, region) {
                switch (code) {
                case "us":
                    window.location.replace("/tagged?tag=US");
                    break;
                case "ca":
                    window.location.replace("/tagged?tag=Canada");
                    break;
                case "mx":
                    window.location.replace("/tagged?tag=Mexico");
                    break;
                    }
                },
            onRegionOver: function (event, code, region) {
               document.body.style.cursor = "pointer";
                },
            onRegionOut: function (element, code, region) {
                   document.body.style.cursor = "default";
                }
        });
      });
    </script>
    </head>

    <body>

    <% content_for :javascripts do %>
      <script type="text/javascript">
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'gmap'}}, function(){
          markers = handler.addMarkers(<%= raw @hash.to_json %>);

          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
      </script>
    <% end %>
    <div>
      <div id="gmap" class="mmap" style='width: 100%'></div>
    </div>

      <h3><img src="https://res.cloudinary.com/ottle/image/upload/t_media_lib_thumb/v1424609566/fafootprint_fi99kd.jpg" style="height: 50px">Footprints</h3>

      <% @posts.each do |post| %>
        <div class="col-md-4">
          <div class="panel panel-info" style="width: 285px; height: 330px;">
            <div class="panel-heading">
              <h2 class="panel-title"><%= link_to post.title, post %></h2>
            </div>
            <div class="panel-body">
              <div class="postThumb col-md-12">
                <%= link_to image_tag(post.image.url), post , class: "img-thumbnail thumbnail"%>
              </div>
              <div>
                  <p>
                    <b>From: </b><%= post.FromDate %><br>
                    <b>To: </b><%= post.ToDate %>
                  </p>
                  <p>
                    <% post.tags.any? %>
                      <% post.tags.each do |tag| %>
                        <%= link_to tag.name, tagged_url(:tag => tag.name), class: "btn btn-default btn-xs" %>
                      <% end %><br><br>
                    <% if user_signed_in? %>
                      <%= link_to 'edit', edit_post_path(post), class: "glyphicon glyphicon-edit" %>
                    <% end %>
                  </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </body>

  <br>

  <% if user_signed_in? %>
    <%= link_to '', new_post_path, class: "glyphicon glyphicon-plus-sign"%>
    <%= link_to '', post_attachments_path, class: "glyphicon glyphicon-list-alt"%>
  <% end %>
  <div class="col-md-12 col-sm-12">
    <hr class="featurette-divider">
    <h4>Tagged Locations</h4>
    <div id="vmap" style="width: 100%; height: 300px;" class="col-md-12"></div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<h1>New post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<script type="text/javascript">
  $(document).ready(function() {
   
    $("#owlshow").owlCarousel({
      navigation: true,
      pagination: false,
      dots: false,
      lazyLoad : true,
      items: 5,
      transitionStyle : "fade",
      itemsDesktop : [1119, 3],
      itemsDesktopSmall : [979, 3],
      autoHeight : true,
      loop : true
    });
   
  });
</script>
<body>
<div class="container">
		<div class="row">
		<h2>
		  <strong><%= @post.title %></strong>
		</h2>
		<div id="owlshow" class="owl-carousel col-md-12">
			<% @post_attachments.each do |p| %>
				<%= link_to image_tag(p.avatar_url), edit_post_attachment_path(p)%>
			<% end %>
		</div>
		<br>
		<div class="col-md-12 col-sm-12 col-lg-12" style="height:15px"></div>
		<div class="col-md-7">
		    <% content_for :javascripts do %>
		      <%= javascript_tag do %>
		      	var lat = <%= @post.latitude.to_json %>
		      	var long = <%= @post.longitude.to_json %>
				handler = Gmaps.build('Google');
				handler.buildMap({ provider: {},internal: {id: 'amap'}},function(){
				    markers = handler.addMarkers([
				      {
				        "lat": lat,
				        "lng": long,
				      }
				    ]);
				    handler.bounds.extendWith(markers);
				    handler.fitMapToBounds();
				    handler.getMap().setZoom(12);
				  });
		      <% end %>
		    <% end %>
		    <div>
		      <div id="amap" style='width: 100%; height: 260px;'></div>
		    </div>
		</div>
		
		<div class="col-md-5">
			<%= image_tag @post.image.url, class: "img-rounded img-thumbnail", :style => "width:100%; max-height:200px" %>
		</div>
		<div class="col-md-5">
			<br>
			<b>Where: </b><%= @post.address %>&nbsp
		</div>
		<div class="col-md-5">
			<b>From: </b><%= @post.FromDate.strftime("%d %b %Y") %>&nbsp&nbsp&nbsp
			<b>To: </b><%= @post.ToDate.strftime("%d %b %Y") %>
		</div>

		<div class="col-md-12 col-sm-12">
			<div class="container-fluid"><br><br>
				<%=simple_format h @post.description %>
			</div>

			<!-- The Bootstrap Image Gallery lightbox, should be a child element of the document body -->
			<div id="blueimp-gallery" class="blueimp-gallery">
				<div class="slides"></div>
				<h3 class="title"></h3>
				<a class="prev">‹</a>
				<a class="next">›</a>
				<a class="close">×</a>
				<a class="play-pause"></a>
				<ol class="indicator"></ol>
			</div>
			<h4><b>Image Gallery</b></h4>
			<div id="links">
				<% @post_attachments.each do |p| %>
					<%= link_to(image_tag(p.avatar_url, :style => "width: 75px"), p.avatar_url, :data => {:gallery => ''}) %>
				<% end %>
			</div>
			<div class="col-md-12 col-sm-12">&nbsp
				<div class ="col-md-12 col-sm-12">Tags: 
				    <% @post.tags.any? %>
				    	<% @post.tags.each do |tag| %>
				        	<%= link_to tag.name, tagged_url(:tag => tag.name), class: "btn btn-default btn-xs" %>
				        <% end %>
				</div>
			</div>

			&nbsp
			 <div id="disqus_thread"></div>
			    <script type="text/javascript">
			        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
			        var disqus_shortname = 'ottle'; // required: replace example with your forum shortname

			        /* * * DON'T EDIT BELOW THIS LINE * * */
			        (function() {
			            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
			            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
			            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
			        })();
			    </script>
			    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    
		&nbsp&nbsp
		</div>

		<div class="col-md-12 col-sm-12">
		<br>
			<%= link_to '', posts_path, class: "glyphicon glyphicon-arrow-left" %> |
			<% if user_signed_in? %>
				<%= link_to '', edit_post_path(@post), class: "glyphicon glyphicon-edit" %> |
				<%= link_to '', post_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash" %>
			<% end %>
		</div>
	</div>
</div>





</body>

app/views/posts/tagged.html.erb
<div class="container">  
  <head>
    <script type="text/javascript">
    jQuery(document).ready(function() {
      jQuery('#vmapus').vectorMap(
      {
          map: 'usa_en',
          backgroundColor: '#a5bfdd',
          borderColor: '#818181',
          borderOpacity: 0.25,
          borderWidth: 1,
          color: '#f4f3f0',
          enableZoom: false,
          hoverColor: '#c9dfaf',
          hoverOpacity: null,
          normalizeFunction: 'linear',
          scaleColors: ['#b6d6ff', '#005ace'],
          selectedColor: '#c9dfaf',
          selectedRegion: null,
          showTooltip: true,
          onRegionClick: function (event, code, region) {
              switch (code) {
              case "ca":
                  window.location.replace("/tagged?tag=California");
                  break;
              case "hi":
                  window.location.replace("/tagged?tag=Hawaii");
                  break;
              case "fl":
                  window.location.replace("/tagged?tag=Florida");
                  break;
                  }
              },
          onRegionOver: function (event, code, region) {
             document.body.style.cursor = "pointer";
              },
          onRegionOut: function (element, code, region) {
                 document.body.style.cursor = "default";
              }
      });
    });
    </script>
  </head>

  <body>
    
    <h3>Tagged</h3>
    <div id="vmapus" style="width: 100%; height: 300px;"></div>
    <div style="height:20px"></div>
    <% @posts.each do |post| %>
      <div class="thumbnail">
        <h2><%= link_to post.title, post %></h2>
        <% post.tags.any? %>
          <% post.tags.each do |tag| %>
            <%= link_to tag.name, tagged_url(:tag => tag.name), class: "btn btn-default btn-xs" %>
        <% end %><br><br>
        <p>
          <%= link_to '', edit_post_path(post), class: "glyphicon glyphicon-edit" %>
        </p>

      </div>
    <% end %>
    <% if user_signed_in? %>
      <%= link_to '', new_post_path, class: "glyphicon glyphicon-plus-sign"%>
      <%= link_to '', post_attachments_path, class: "glyphicon glyphicon-list-alt"%>
    <% end %>
  </body>

<br>
</div>