config/routes.rb
Rails.application.routes.draw do
  
  get 'tag/show'

  resources :post_attachments
  resources :posts

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/investment'
  get 'pages/csprojects'
  
  get 'seller' => 'listings#seller'
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  get 'tagged' => 'posts#tagged'
  get 'users' => 'users#index'

  root 'pages#home'

end

app/views/layouts/_footer.html.erb
<br>
&nbsp
<div class="container-fluid footer">
	<div class="container">
		<br>
		<p class="pull-right"><a href="#"><i class="fa fa-arrow-up white"></i></a></p>
		<p><span class="brandcolor">&copy; 2015 Ottle, Inc.</span> &middot; <a href="#" class="white">Privacy</a> &middot; <a href="#" class="white">Terms</a></p>
	</div>
	<%= yield :javascripts %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar-inverse" role="navigation">
   
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span> 
          <span class="icon-bar"></span> 
          <span class="icon-bar"></span> 
          <!-- <span class="glyphicon glyphicon-list white" style="font-size: 20px"></span>-->
        </button>
        <a class="navbarbrand navbar-brand" href="/">otl</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <nav class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "about me", pages_about_path %></li>
                <li><%= link_to "contact", pages_contact_path %></li>
              </ul
          </li>
          <li><%= link_to "Travel Blog", posts_path %></li>
          <li><%= link_to "Investment", pages_investment_path %></li>
          <li><%= link_to "CS Projects", pages_csprojects_path %></li>
        </ul>


        <ul class="nav navbar-nav navbar-right">
              <li>
                <a href="/listings">
                <span class="glyphicon glyphicon-shopping-cart fa-lg"></span>
                </a>
              </li>
              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Seller Account<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Manage Listings", seller_path %></li>
                    <li><%= link_to "Sales History", sales_path %></li>
                  </ul>
                </li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user"></span><%= current_user.name %><span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Purchase History", purchases_path %></li>
                    <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                  </ul>
                </li>
     
              <% else %>
                <li>
                  <a href="/users/auth/facebook">
                    <i class="fa fa-facebook-official fa-lg"></i>
                  </a>
                </li>
                <li>
                  <a href="/users/sign_in">
                    <i class="fa fa-sign-in fa-lg"></i>
                  </a>
                </li>
                <li>
                  <%= link_to "Sign Up", new_user_registration_path %>
                </li>
              <% end %>
  

          </li>
        </ul>
      </nav><!-- /.navbar-collapse -->
  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Ottle</title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
<!--CSS-->
	  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" %>
	<!--Image Gallery-->
	  <%= stylesheet_link_tag "//blueimp.github.io/Gallery/css/blueimp-gallery.min.css" %>
	  <!--<%= stylesheet_link_tag "css/bootstrap-image-gallery.min.css" %>-->
<!--JS-->
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<!--Charts-->
	  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
      <%= javascript_include_tag "http://code.highcharts.com/stock/highstock.js" %>
      <%= javascript_include_tag "http://code.highcharts.com/stock/modules/exporting.js" %>
	<!--Stripe-->
	  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
	<!--Google Map-->
	  <%= javascript_include_tag "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" %>
	  <%= javascript_include_tag '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js'  %>
	<!--Image Gallery-->
	  <%= javascript_include_tag "//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js" %>
	  <!--<%= javascript_include_tag "js/bootstrap-image-gallery.min.js" %>-->

	  <%= javascript_include_tag "vendor/modernizr" %>
	  <%= csrf_meta_tags %>
	  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
	  <%= yield(:head) %>
	</head>
	<body>
			<%= render 'layouts/header' %>
			<!-- 
			<p class="notice"><%= notice %></p>
			<p class="alert"><%= alert %></p> 
			-->
			<div class="container-fluid">
				<% flash.each do |name, msg| %>
					<% if msg.is_a?(String) %>
						<br>
						<div class="alert alert-<%= name.to_s == 'notice' ? "success" : "danger" %> alert-dismissable">
							<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
							<%= content_tag :div, msg, :id => "flash_#{name}" %>
						</div>
					<% end %>
				<% end %>
			</div>

			<%= yield %>

			<%= render 'layouts/footer' %>


	</body>
</html>